export const data = {
    "vm":
        [
            "ROOT1",
            "ROOT2",
            "ROOT3"
        ],
    "subfolders":
    {
        "정보통신학교":
        {
            "vm":
                [],
            "subfolders":
            {
                "실습인프라":
                {
                    "vm":
                        [
                            "ad"
                        ],
                    "subfolders":
                        {}
                },
                "시나리오":
                {
                    "vm":
                        [],
                    "subfolders":
                    {
                        "7":
                        {
                            "vm":
                                [
                                    "NTP",
                                    "NAC",
                                    "AdminConsole2",
                                    "sensor(vpn)",
                                    "Router1",
                                    "Web Server",
                                    "User01-PC",
                                    "sensor(inter)",
                                    "Attacker",
                                    "User03-PC",
                                    "Public-PC",
                                    "DNS",
                                    "AdminConsole1",
                                    "Mail Server",
                                    "C2",
                                    "UTM",
                                    "User02-PC",
                                    "Router2"
                                ],
                            "subfolders":
                                {}
                        },
                        "4":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        },
                        "3":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        },
                        "2":
                        {
                            "vm":
                                [
                                    "T_DNS-2",
                                    "T_Web Server-2",
                                    "T_Router2-2",
                                    "T_NTP-2",
                                    "T_User03-PC-2",
                                    "T_Attacker-2",
                                    "T_User02-PC-2",
                                    "T_NAC-2",
                                    "T_Router1-2",
                                    "T_AdminConsole2-2",
                                    "T_AdminConsole1-2",
                                    "T_Mail Server-2",
                                    "T_Public-PC-2",
                                    "T_sensor(vpn)-2",
                                    "T_C2-2",
                                    "T_User01-PC-2",
                                    "T_sensor(inter)-2"
                                ],
                            "subfolders":
                                {}
                        },
                        "1":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        },
                        "5":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        },
                        "6":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        }
                    }
                }
            }
        },
        "시나리오템플릿":
        {
            "vm":
                [],
            "subfolders":
            {
                "Blue Team":
                {
                    "vm":
                        [],
                    "subfolders":
                    {
                        "B1":
                        {
                            "vm":
                                [
                                    "B1_INTER-DNS_TP",
                                    "B1_ROUTER1_TP",
                                    "B1_GRADE_TP",
                                    "B1_WIN10_TP",
                                    "B1_UBUNTU3_TP",
                                    "B1_ROUTER3_TP",
                                    "B1_RPROXY_TP",
                                    "B1_UBUNTU1_TP",
                                    "B1_UBUNTU2_TP",
                                    "B1_ROUTER2_TP",
                                    "B1_KALI_TP",
                                    "B1_WIN10-2_TP"
                                ],
                            "subfolders":
                                {}
                        }
                    }
                },
                "Red Team":
                {
                    "vm":
                        [],
                    "subfolders":
                    {
                        "R1":
                        {
                            "vm":
                                [
                                    "R1_WIN7_TP",
                                    "R1_DNS_TP",
                                    "R1_KALI_TP",
                                    "R1_SWITCH_TP",
                                    "R1_ROUTER4_TP",
                                    "R1_ROUTER1_TP",
                                    "R1_WS2012_TP",
                                    "R1_WIN7-2_TP",
                                    "R1_UBUNTU_TP",
                                    "R1_ROUTER2_TP",
                                    "R1_ROUTER3_TP",
                                    "R1_MAIL_TP"
                                ],
                            "subfolders":
                                {}
                        }
                    }
                }
            }
        }
    }
}
