export const data = {
    "vm":
        [
            "B1_V2_ROUTER3_104",
            "B1_V7_RPROXY_104",
            "B1_V1_KALI_104",
            "B1_V4_ROUTER2_104",
            "R1_V1_DNS_102",
            "B1_V8_UBUNTU3_104",
            "R1_V2_SWITCH_102",
            "shellshock2",
            "shellshock",
            "T_Ubuntu2",
            "Web Server-5",
            "DNS-6",
            "User01-PC-6",
            "새 가상 시스템",
            "sensor(vpn)-2",
            "C2-1-test",
            "AdminConsole1-1-test",
            "[AIO] VM,CHAL",
            "sensor(vpn)-7",
            "User01-PC-2",
            "C2-4",
            "signal_Win7-2",
            "R1_V3_KALI_102",
            "[AIO] GYM_DEV_HJ",
            "DNS-3",
            "NAC-3",
            "B1_V6_UBUNTU1_104",
            "sensor_vpn_-2-copy",
            "Public-PC-5",
            "sensor(inter)-4",
            "unit_tec_Public",
            "Router1_실습-1",
            "User02_실습-1",
            "Public-PC-실습-1",
            "R1_V6_ROUTER2_102",
            "signal_nacS",
            "DNS-4",
            "AdminConsole2-6",
            "Router1-6",
            "NTP-7",
            "signal_AX",
            "Web Server_실습-2",
            "C2-2-copy",
            "unit_Tec_R4",
            "NAC-2-copy",
            "unit_tec_AdminConsole",
            "UTM-실습(copy)",
            "unit_tec_Ax",
            "AdminConsole1-6",
            "T_DNS",
            "Public-PC_2-4",
            "AdminConsole2-2",
            "sensor(inter)-2",
            "Attacker_2-4",
            "VMware vCenter Server",
            "Public-PC-2-copy",
            "Mail Server-1-test",
            "Public-PC-4",
            "AdminConsole1-2-copy",
            "B1_V11_WIN10-2_104",
            "NTP_실습-1",
            "User01-PC-2-copy",
            "NAC-7 dump",
            "UTM-3-copy",
            "ub test",
            "Net_wireshark",
            "DNS_실습-1",
            "sensor_vpn_-3-copy",
            "younggil2",
            "User03-PC-3-copy",
            "Web Server_실습-1",
            "R1_V12_WIN7_102",
            "signal_Attack",
            "unit_Tec_kali",
            "sensor(inter)-7",
            "Web Server-3-copy",
            "sensor_inter_-2-copy",
            "C2-7",
            "User01-PC-4",
            "unit_Tec_R2",
            "Router2-2-copy",
            "User03-PC-7",
            "Web Server-4",
            "AdminConsole2-2-copy",
            "User02-PC-5",
            "ckeditor_test",
            "Attacker-3-copy",
            "NTP-6",
            "[AIO] CHAL",
            "AdminConsole1-2",
            "unit_tec_User1",
            "Router1-3-copy",
            "C2-6",
            "B1_V5_INTER-DNS_104",
            "NTP-5",
            "sensor_inter_-1-test",
            "Router2-3-copy",
            "AdminConsole2-1-test",
            "sensor_vpn_-1-test",
            "R1_V5_ROUTER1_102",
            "User01-PC-3",
            "UTM-실습(setting)",
            "Network_MAIL",
            "B1_test_Ubuntu1",
            "Mail Server-2-copy",
            "User02-PC-4",
            "Router2_실습-1",
            "Attacker-2",
            "UTM-6",
            "Router1-1-test",
            "signal_C2",
            "sensor(vpn)-5",
            "User02-PC-3-copy",
            "AdminConsole1-5",
            "Router2-3",
            "Router2-6",
            "User02-PC-2",
            "signal_Win7",
            "User03-PC-5",
            "Router2-4",
            "Attacker-5",
            "AdminConsole1_실습-1",
            "AdminConsole2-4",
            "User01-PC-7",
            "Router2-2",
            "User02-PC-1-test",
            "T_R1",
            "unit_tec_nacS",
            "T_R2",
            "DNS-3-copy",
            "T_Kali",
            "sensor(inter)-3",
            "R1_V8_ROUTER4_102",
            "Router1-3",
            "unit_tec_DNS",
            "User03-PC-6",
            "Public-PC-7",
            "AdminConsole1-3",
            "Attacker_3-4",
            "Web Server-3",
            "win10_hojin",
            "AdminConsole1-4",
            "Mail Server-3",
            "B1_V10_GRADE_104",
            "AdminConsole2-7",
            "C2-5",
            "UTM-실습(setting2)",
            "User03-PC-2",
            "WP_TEST",
            "User02-PC-3",
            "Attacker-3",
            "sensor(vpn)-4",
            "NAC-실습",
            "NAC-6",
            "T_I_DNS",
            "AdminConsole2-5",
            "NAC-3-copy",
            "UTM-2",
            "Public-PC-3-copy",
            "Mail Server-2",
            "T_G-Server",
            "Public-PC-1-test",
            "Mail Server-4",
            "AdminConsole2-3",
            "Public-PC-6",
            "User02-PC-7",
            "unit_Tec_R1",
            "AdminConsole2-3-copy",
            "NAC-1-test",
            "Public-PC-2",
            "signal_Mail",
            "Attacker-4",
            "Mail Server-5",
            "R1_V10_WS2012_102",
            "Attacker_실습-1",
            "User03-PC-2-copy",
            "DNS-2",
            "signal_Ewin10",
            "B1_test_Ubuntu2",
            "NTP-2-copy",
            "UTM-2-copy",
            "R1_UBUNTU_Advancement",
            "[AIO] GYM_DEV",
            "UTM-5",
            "win10_1511_2",
            "[AIO] GYM_DEV_SJ",
            "NAC-5",
            "NAC-2",
            "Router1-2",
            "Public-PC_3-4",
            "sensor(vpn)-6",
            "Attacker-7",
            "Public-PC-3",
            "B1_test_Ubuntu3",
            "Web Server-7",
            "Router1-4",
            "Mail Server-3-copy",
            "R1_V4_MAIL_102",
            "sensor(inter)_실습-1",
            "unit_Tec_R3",
            "sensor(inter)-6",
            "Router2-7",
            "DNS-2-copy",
            "User03-PC-1-test",
            "R1_V7_ROUTER3_102",
            "AdminConsole1-실습(테스트용)",
            "NAC-4",
            "Web Server-2",
            "AdminConsole1-7",
            "Mail Server-6",
            "User02-PC-6",
            "Attacker-2-copy",
            "Router1-7",
            "signal_admin(win10)",
            "NTP-1-test",
            "T_Win10_1511_32",
            "B1_V9_WIN10_104",
            "signal_ntp",
            "unit_tec_User2",
            "sensor(inter)-5",
            "DNS-5",
            "enginx",
            "NTP-2",
            "unit_tec_nacC",
            "C2-3-copy",
            "Router2-5",
            "UTM-7",
            "signal_U20",
            "T_FUbuntu1",
            "User03-PC-3",
            "Attacker-6",
            "R1_V11_WIN7-2_102",
            "T_Win10_32",
            "T_Wubuntu",
            "siganl_web3_2",
            "Attacker-1-test",
            "C2-3",
            "User01_실습-1",
            "signal_R1",
            "ubuntu(pure)",
            "User01-PC-5",
            "User01-PC-1-test",
            "NTP-3",
            "AdminConsole1-3-copy",
            "T_Ubuntu",
            "Web Server-6",
            "User01-PC-3-copy",
            "signal_nsV",
            "Web Server-1-test",
            "signal_web2",
            "Router1-5",
            "signal_ad",
            "packetfense_NAC",
            "sensor_inter_-3-copy",
            "UTM-4",
            "PacketFence-ZEN",
            "DNS-1-test",
            "NTP-3-copy",
            "UTM-1-test",
            "UTM-실습",
            "NAC-실습(setting)",
            "T_R3",
            "DNS-7",
            "NAC-7",
            "siganl_win7_attacker",
            "NTP-4",
            "R1_V9_UBUNTU_102",
            "Pic_WUbuntu",
            "C2-2",
            "User03-PC-4",
            "Router2-1-test",
            "sensor(vpn)-3",
            "signal_web3",
            "signal_nacC",
            "signal_win10",
            "UTM-3",
            "unit_Tec_Ub",
            "B1_V3_ROUTER1_104",
            "Mail Server-7",
            "signal_DNS",
            "Web Server-2-copy",
            "pfsense-test",
            "Router1-2-copy",
            "User02-PC-2-copy",
            "signal_R2"
        ],
    "subfolders":
    {
        "정보통신학교":
        {
            "vm":
                [],
            "subfolders":
            {
                "실습인프라":
                {
                    "vm":
                        [
                            "ad"
                        ],
                    "subfolders":
                        {}
                },
                "시나리오":
                {
                    "vm":
                        [],
                    "subfolders":
                    {
                        "7":
                        {
                            "vm":
                                [
                                    "NTP",
                                    "NAC",
                                    "AdminConsole2",
                                    "sensor(vpn)",
                                    "Router1",
                                    "Web Server",
                                    "User01-PC",
                                    "sensor(inter)",
                                    "Attacker",
                                    "User03-PC",
                                    "Public-PC",
                                    "DNS",
                                    "AdminConsole1",
                                    "Mail Server",
                                    "C2",
                                    "UTM",
                                    "User02-PC",
                                    "Router2"
                                ],
                            "subfolders":
                                {}
                        },
                        "4":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        },
                        "3":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        },
                        "2":
                        {
                            "vm":
                                [
                                    "T_DNS-2",
                                    "T_Web Server-2",
                                    "T_Router2-2",
                                    "T_NTP-2",
                                    "T_User03-PC-2",
                                    "T_Attacker-2",
                                    "T_User02-PC-2",
                                    "T_NAC-2",
                                    "T_Router1-2",
                                    "T_AdminConsole2-2",
                                    "T_AdminConsole1-2",
                                    "T_Mail Server-2",
                                    "T_Public-PC-2",
                                    "T_sensor(vpn)-2",
                                    "T_C2-2",
                                    "T_User01-PC-2",
                                    "T_sensor(inter)-2"
                                ],
                            "subfolders":
                                {}
                        },
                        "1":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        },
                        "5":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        },
                        "6":
                        {
                            "vm":
                                [],
                            "subfolders":
                                {}
                        }
                    }
                }
            }
        },
        "시나리오템플릿":
        {
            "vm":
                [],
            "subfolders":
            {
                "Blue Team":
                {
                    "vm":
                        [],
                    "subfolders":
                    {
                        "B1":
                        {
                            "vm":
                                [
                                    "B1_INTER-DNS_TP",
                                    "B1_ROUTER1_TP",
                                    "B1_GRADE_TP",
                                    "B1_WIN10_TP",
                                    "B1_UBUNTU3_TP",
                                    "B1_ROUTER3_TP",
                                    "B1_RPROXY_TP",
                                    "B1_UBUNTU1_TP",
                                    "B1_UBUNTU2_TP",
                                    "B1_ROUTER2_TP",
                                    "B1_KALI_TP",
                                    "B1_WIN10-2_TP"
                                ],
                            "subfolders":
                                {}
                        }
                    }
                },
                "Red Team":
                {
                    "vm":
                        [],
                    "subfolders":
                    {
                        "R1":
                        {
                            "vm":
                                [
                                    "R1_WIN7_TP",
                                    "R1_DNS_TP",
                                    "R1_KALI_TP",
                                    "R1_SWITCH_TP",
                                    "R1_ROUTER4_TP",
                                    "R1_ROUTER1_TP",
                                    "R1_WS2012_TP",
                                    "R1_WIN7-2_TP",
                                    "R1_UBUNTU_TP",
                                    "R1_ROUTER2_TP",
                                    "R1_ROUTER3_TP",
                                    "R1_MAIL_TP"
                                ],
                            "subfolders":
                                {}
                        }
                    }
                }
            }
        }
    }
}
